{% set name = "FastMLST" %}
{% set version = "0.0.5" %}
{% set user = "EnzoAndree" %}
{% set sha256 = "a98e71a496032adf531f6754dcb5ab75b0c452a012986777a626373c67f03417" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

source:
  url: https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

requirements:
  build:
    - python>=3
  run:
    - python>=3
    - tqdm
    - pandas
    - blast
    - biopython

test:
  commands:
    - {{ name|lower }} -V

about:
  home: https://github.com/{{ user }}/{{ name }}
  summary: A Fast Multilocus Sequence Typing scan against PubMLST typing schemes
  license: LGPL-3.0
