{% set version = "0.1.1" %}

package:
  name: svim-asm
  version: '{{ version }}'

source:
  url: https://github.com/eldariont/svim-asm/archive/v{{ version }}.tar.gz
  sha256: 3557eba481a2faceebb17dc30ba7e218157935c09c70da6772ef7e7f4097f8b7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pysam >=0.15
    - numpy
    - scipy
    - matplotlib
    - python-edlib

test:
  commands:
    - svim-asm -h

about:
  home: 'https://github.com/eldariont/svim-asm'
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: SVIM-asm is a fork of the SV caller SVIM for genome-genome alignments.

